### ISSUE TITLE
Can't Authenticate with Spotify App Installed :bug:

### ISSUE THREAD

**Issue by ejschenck** [insidegui/AnimojiStudio#28] opened 2017-12-28 03:34 UTC
When I attempt to authenticate Spotify and have the actual spotify app on my iPhone, it will open the App then come right back to AnimojiStudio without asking for permissions.

If I delete Spotify, a web browser comes up with the ability to login to Spotify and everything works fine.

This appears to not be how it's supposed to work according to the app description.

**Comment by insidegui** [comment] 2017-12-28 14:11
Is this a duplicate of #17 ?

Did you change de bundle ID of the app? If you did, you have to get your own Spotify client ID and change it [here](https://github.com/insidegui/AnimojiStudio/blob/master/AnimojiStudio/Core/SpotifyCoordinator.m#L49).

I will update the readme with this info.

**Comment by insidegui** [comment] 2017-12-28 14:33
I actually changed the auth flow to only use the webview-based login for now.

**Closed by insidegui** 2017-12-28 14:33 UTC
